18/11/2015 08:02:43 p.m. - ---------------------------------------------
18/11/2015 08:02:43 p.m. - System.ServiceModel.FaultException: System.Web.Services.Protocols.SoapException: El servidor no puede procesar la solicitud. ---> System.Exception: lauraaa
   en General.MAU.RepositorioDeFuncionalidades.<>c__DisplayClass1.<GetFuncionalidadesDeTablaDeDatos>b__0(RowDeDatos row) en C:\Repositorios\FernandoAssembla\Git_SistemaWeb\rrhh2\rrhh\ProyectoNet\General\MAU\RepositorioDeFuncionalidades.cs:línea 42
   en System.Collections.Generic.List`1.ForEach(Action`1 action)
   en General.MAU.RepositorioDeFuncionalidades.GetFuncionalidadesDeTablaDeDatos(TablaDeDatos tablaDatos) en C:\Repositorios\FernandoAssembla\Git_SistemaWeb\rrhh2\rrhh\ProyectoNet\General\MAU\RepositorioDeFuncionalidades.cs:línea 33
   en General.MAU.RepositorioDeFuncionalidades.ObtenerDesdeLaBase() en C:\Repositorios\FernandoAssembla\Git_SistemaWeb\rrhh2\rrhh\ProyectoNet\General\MAU\RepositorioDeFuncionalidades.cs:línea 56
   en General.Repositorios.RepositorioLazySingleton`1.Obtener() en C:\Repositorios\FernandoAssembla\Git_SistemaWeb\rrhh2\rrhh\ProyectoNet\General\Repositorios\RepositorioLazySingleton.cs:línea 38
   en General.MAU.RepositorioDeFuncionalidades.TodasLasFuncionalidades() en C:\Repositorios\FernandoAssembla\Git_SistemaWeb\rrhh2\rrhh\ProyectoNet\General\MAU\RepositorioDeFuncionalidades.cs:línea 27
   en General.MAU.RepositorioDeAccesosAURL.ObtenerDesdeLaBase() en C:\Repositorios\FernandoAssembla\Git_SistemaWeb\rrhh2\rrhh\ProyectoNet\General\MAU\RepositorioDeAccesosAURL.cs:línea 48
   en General.Repositorios.RepositorioLazySingleton`1.Obtener() en C:\Repositorios\FernandoAssembla\Git_SistemaWeb\rrhh2\rrhh\ProyectoNet\General\Repositorios\RepositorioLazySingleton.cs:línea 38
   en General.MAU.RepositorioDeAccesosAURL.TodosLosAccesos() en C:\Repositorios\FernandoAssembla\Git_SistemaWeb\rrhh2\rrhh\ProyectoNet\General\MAU\RepositorioDeAccesosAURL.cs:línea 42
   en General.MAU.Autorizador.ElUsuarioPuedeAccederALaURL(Usuario usuario, String url) en C:\Repositorios\FernandoAssembla\Git_SistemaWeb\rrhh2\rrhh\ProyectoNet\General\MAU\Autorizador.cs:línea 137
   en WSViaticos.ElUsuarioPuedeAccederALaURL(Usuario usuario, String url) en c:\Repositorios\FernandoAssembla\Git_SistemaWeb\rrhh2\rrhh\WebAsistencia\WSViaticos\App_Code\WSViaticos.cs:línea 2016
   --- Fin del seguimiento de la pila de la excepción interna ---

Server stack trace: 
   en System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   en System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   en System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   en System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   en System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   en System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   en WSViaticos.WSViaticosSoap.ElUsuarioPuedeAccederALaURL(Usuario usuario, String url)
   en WSViaticos.WSViaticosSoapClient.ElUsuarioPuedeAccederALaURL(Usuario usuario, String url) en c:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\webrh\936eec72\4a47507\App_WebReferences.lbeccbhh.0.cs:línea 12790
   en ASP.global_asax.Application_AcquireRequestState(Object sender, EventArgs e) en c:\Repositorios\FernandoAssembla\Git_SistemaWeb\rrhh2\rrhh\WebAsistencia\WebRH\Global.asax:línea 16
   en System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   en System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
18/11/2015 08:22:39 p.m. - ---------------------------------------------
18/11/2015 08:22:39 p.m. - System.ServiceModel.FaultException: System.Web.Services.Protocols.SoapException: El servidor no puede procesar la solicitud. ---> System.Exception: lauraaa
   en General.MAU.RepositorioDeFuncionalidades.<>c__DisplayClass1.<GetFuncionalidadesDeTablaDeDatos>b__0(RowDeDatos row) en C:\Repositorios\FernandoAssembla\Git_SistemaWeb\rrhh2\rrhh\ProyectoNet\General\MAU\RepositorioDeFuncionalidades.cs:línea 42
   en System.Collections.Generic.List`1.ForEach(Action`1 action)
   en General.MAU.RepositorioDeFuncionalidades.GetFuncionalidadesDeTablaDeDatos(TablaDeDatos tablaDatos) en C:\Repositorios\FernandoAssembla\Git_SistemaWeb\rrhh2\rrhh\ProyectoNet\General\MAU\RepositorioDeFuncionalidades.cs:línea 33
   en General.MAU.RepositorioDeFuncionalidades.ObtenerDesdeLaBase() en C:\Repositorios\FernandoAssembla\Git_SistemaWeb\rrhh2\rrhh\ProyectoNet\General\MAU\RepositorioDeFuncionalidades.cs:línea 56
   en General.Repositorios.RepositorioLazySingleton`1.Obtener() en C:\Repositorios\FernandoAssembla\Git_SistemaWeb\rrhh2\rrhh\ProyectoNet\General\Repositorios\RepositorioLazySingleton.cs:línea 38
   en General.MAU.RepositorioDeFuncionalidades.TodasLasFuncionalidades() en C:\Repositorios\FernandoAssembla\Git_SistemaWeb\rrhh2\rrhh\ProyectoNet\General\MAU\RepositorioDeFuncionalidades.cs:línea 27
   en General.MAU.RepositorioDeAccesosAURL.ObtenerDesdeLaBase() en C:\Repositorios\FernandoAssembla\Git_SistemaWeb\rrhh2\rrhh\ProyectoNet\General\MAU\RepositorioDeAccesosAURL.cs:línea 48
   en General.Repositorios.RepositorioLazySingleton`1.Obtener() en C:\Repositorios\FernandoAssembla\Git_SistemaWeb\rrhh2\rrhh\ProyectoNet\General\Repositorios\RepositorioLazySingleton.cs:línea 38
   en General.MAU.RepositorioDeAccesosAURL.TodosLosAccesos() en C:\Repositorios\FernandoAssembla\Git_SistemaWeb\rrhh2\rrhh\ProyectoNet\General\MAU\RepositorioDeAccesosAURL.cs:línea 42
   en General.MAU.Autorizador.ElUsuarioPuedeAccederALaURL(Usuario usuario, String url) en C:\Repositorios\FernandoAssembla\Git_SistemaWeb\rrhh2\rrhh\ProyectoNet\General\MAU\Autorizador.cs:línea 137
   en WSViaticos.ElUsuarioPuedeAccederALaURL(Usuario usuario, String url) en c:\Repositorios\FernandoAssembla\Git_SistemaWeb\rrhh2\rrhh\WebAsistencia\WSViaticos\App_Code\WSViaticos.cs:línea 2016
   --- Fin del seguimiento de la pila de la excepción interna ---

Server stack trace: 
   en System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   en System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   en System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   en System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   en System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   en System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   en WSViaticos.WSViaticosSoap.ElUsuarioPuedeAccederALaURL(Usuario usuario, String url)
   en WSViaticos.WSViaticosSoapClient.ElUsuarioPuedeAccederALaURL(Usuario usuario, String url) en c:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\webrh\936eec72\4a47507\App_WebReferences.3xokzxzl.0.cs:línea 12790
   en ASP.global_asax.Application_AcquireRequestState(Object sender, EventArgs e) en c:\Repositorios\FernandoAssembla\Git_SistemaWeb\rrhh2\rrhh\WebAsistencia\WebRH\Global.asax:línea 16
   en System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   en System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
18/11/2015 08:31:26 p.m. - ---------------------------------------------
18/11/2015 08:31:26 p.m. - System.ServiceModel.FaultException: System.Web.Services.Protocols.SoapException: El servidor no puede procesar la solicitud. ---> System.Exception: lauraaa
   en General.MAU.RepositorioDeFuncionalidades.<>c__DisplayClass1.<GetFuncionalidadesDeTablaDeDatos>b__0(RowDeDatos row) en C:\Repositorios\FernandoAssembla\Git_SistemaWeb\rrhh2\rrhh\ProyectoNet\General\MAU\RepositorioDeFuncionalidades.cs:línea 42
   en System.Collections.Generic.List`1.ForEach(Action`1 action)
   en General.MAU.RepositorioDeFuncionalidades.GetFuncionalidadesDeTablaDeDatos(TablaDeDatos tablaDatos) en C:\Repositorios\FernandoAssembla\Git_SistemaWeb\rrhh2\rrhh\ProyectoNet\General\MAU\RepositorioDeFuncionalidades.cs:línea 33
   en General.MAU.RepositorioDeFuncionalidades.ObtenerDesdeLaBase() en C:\Repositorios\FernandoAssembla\Git_SistemaWeb\rrhh2\rrhh\ProyectoNet\General\MAU\RepositorioDeFuncionalidades.cs:línea 56
   en General.Repositorios.RepositorioLazySingleton`1.Obtener() en C:\Repositorios\FernandoAssembla\Git_SistemaWeb\rrhh2\rrhh\ProyectoNet\General\Repositorios\RepositorioLazySingleton.cs:línea 38
   en General.MAU.RepositorioDeFuncionalidades.TodasLasFuncionalidades() en C:\Repositorios\FernandoAssembla\Git_SistemaWeb\rrhh2\rrhh\ProyectoNet\General\MAU\RepositorioDeFuncionalidades.cs:línea 27
   en General.MAU.RepositorioDeAccesosAURL.ObtenerDesdeLaBase() en C:\Repositorios\FernandoAssembla\Git_SistemaWeb\rrhh2\rrhh\ProyectoNet\General\MAU\RepositorioDeAccesosAURL.cs:línea 48
   en General.Repositorios.RepositorioLazySingleton`1.Obtener() en C:\Repositorios\FernandoAssembla\Git_SistemaWeb\rrhh2\rrhh\ProyectoNet\General\Repositorios\RepositorioLazySingleton.cs:línea 38
   en General.MAU.RepositorioDeAccesosAURL.TodosLosAccesos() en C:\Repositorios\FernandoAssembla\Git_SistemaWeb\rrhh2\rrhh\ProyectoNet\General\MAU\RepositorioDeAccesosAURL.cs:línea 42
   en General.MAU.Autorizador.ElUsuarioPuedeAccederALaURL(Usuario usuario, String url) en C:\Repositorios\FernandoAssembla\Git_SistemaWeb\rrhh2\rrhh\ProyectoNet\General\MAU\Autorizador.cs:línea 137
   en WSViaticos.ElUsuarioPuedeAccederALaURL(Usuario usuario, String url) en c:\Repositorios\FernandoAssembla\Git_SistemaWeb\rrhh2\rrhh\WebAsistencia\WSViaticos\App_Code\WSViaticos.cs:línea 2016
   --- Fin del seguimiento de la pila de la excepción interna ---

Server stack trace: 
   en System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   en System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   en System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   en System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   en System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   en System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   en WSViaticos.WSViaticosSoap.ElUsuarioPuedeAccederALaURL(Usuario usuario, String url)
   en WSViaticos.WSViaticosSoapClient.ElUsuarioPuedeAccederALaURL(Usuario usuario, String url) en c:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\webrh\936eec72\4a47507\App_WebReferences.3xokzxzl.0.cs:línea 12790
   en ASP.global_asax.Application_AcquireRequestState(Object sender, EventArgs e) en c:\Repositorios\FernandoAssembla\Git_SistemaWeb\rrhh2\rrhh\WebAsistencia\WebRH\Global.asax:línea 16
   en System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   en System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
18/11/2015 08:34:56 p.m. - ---------------------------------------------
18/11/2015 08:34:58 p.m. - System.ServiceModel.FaultException: System.Web.Services.Protocols.SoapException: El servidor no puede procesar la solicitud. ---> System.Exception: lauraaa
   en General.MAU.RepositorioDeFuncionalidades.<>c__DisplayClass1.<GetFuncionalidadesDeTablaDeDatos>b__0(RowDeDatos row) en C:\Repositorios\FernandoAssembla\Git_SistemaWeb\rrhh2\rrhh\ProyectoNet\General\MAU\RepositorioDeFuncionalidades.cs:línea 42
   en System.Collections.Generic.List`1.ForEach(Action`1 action)
   en General.MAU.RepositorioDeFuncionalidades.GetFuncionalidadesDeTablaDeDatos(TablaDeDatos tablaDatos) en C:\Repositorios\FernandoAssembla\Git_SistemaWeb\rrhh2\rrhh\ProyectoNet\General\MAU\RepositorioDeFuncionalidades.cs:línea 33
   en General.MAU.RepositorioDeFuncionalidades.ObtenerDesdeLaBase() en C:\Repositorios\FernandoAssembla\Git_SistemaWeb\rrhh2\rrhh\ProyectoNet\General\MAU\RepositorioDeFuncionalidades.cs:línea 56
   en General.Repositorios.RepositorioLazySingleton`1.Obtener() en C:\Repositorios\FernandoAssembla\Git_SistemaWeb\rrhh2\rrhh\ProyectoNet\General\Repositorios\RepositorioLazySingleton.cs:línea 38
   en General.MAU.RepositorioDeFuncionalidades.TodasLasFuncionalidades() en C:\Repositorios\FernandoAssembla\Git_SistemaWeb\rrhh2\rrhh\ProyectoNet\General\MAU\RepositorioDeFuncionalidades.cs:línea 27
   en General.MAU.RepositorioDeAccesosAURL.ObtenerDesdeLaBase() en C:\Repositorios\FernandoAssembla\Git_SistemaWeb\rrhh2\rrhh\ProyectoNet\General\MAU\RepositorioDeAccesosAURL.cs:línea 48
   en General.Repositorios.RepositorioLazySingleton`1.Obtener() en C:\Repositorios\FernandoAssembla\Git_SistemaWeb\rrhh2\rrhh\ProyectoNet\General\Repositorios\RepositorioLazySingleton.cs:línea 38
   en General.MAU.RepositorioDeAccesosAURL.TodosLosAccesos() en C:\Repositorios\FernandoAssembla\Git_SistemaWeb\rrhh2\rrhh\ProyectoNet\General\MAU\RepositorioDeAccesosAURL.cs:línea 42
   en General.MAU.Autorizador.ElUsuarioPuedeAccederALaURL(Usuario usuario, String url) en C:\Repositorios\FernandoAssembla\Git_SistemaWeb\rrhh2\rrhh\ProyectoNet\General\MAU\Autorizador.cs:línea 137
   en WSViaticos.ElUsuarioPuedeAccederALaURL(Usuario usuario, String url) en c:\Repositorios\FernandoAssembla\Git_SistemaWeb\rrhh2\rrhh\WebAsistencia\WSViaticos\App_Code\WSViaticos.cs:línea 2016
   --- Fin del seguimiento de la pila de la excepción interna ---

Server stack trace: 
   en System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   en System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   en System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   en System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   en System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   en System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   en WSViaticos.WSViaticosSoap.ElUsuarioPuedeAccederALaURL(Usuario usuario, String url)
   en WSViaticos.WSViaticosSoapClient.ElUsuarioPuedeAccederALaURL(Usuario usuario, String url) en c:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\webrh\936eec72\4a47507\App_WebReferences.w4nbgajo.0.cs:línea 12790
   en ASP.global_asax.Application_AcquireRequestState(Object sender, EventArgs e) en c:\Repositorios\FernandoAssembla\Git_SistemaWeb\rrhh2\rrhh\WebAsistencia\WebRH\Global.asax:línea 16
   en System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   en System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
