26/11/2015 09:20:15 p.m. - ---------------------------------------------
26/11/2015 09:20:15 p.m. - System.Web.HttpUnhandledException (0x80004005): Se produjo una excepción de tipo 'System.Web.HttpUnhandledException'. ---> System.ServiceModel.FaultException: System.Web.Services.Protocols.SoapException: El servidor no puede procesar la solicitud. ---> System.Data.SqlClient.SqlException: Los datos de cadena o binarios se truncarían.
Se terminó la instrucción.
   en General.Repositorios.ConexionBDSQL.Ejecutar(String procedimiento, Dictionary`2 parametros) en C:\Repositorios\Belén\rrhh\ProyectoNet\General\Repositorios\ConexionBDSQL.cs:línea 136
   en General.RepositorioDePostulaciones.TableroDeControlPostulaciones() en C:\Repositorios\Belén\rrhh\ProyectoNet\General\Postular\RepositorioDePostulaciones.cs:línea 377
   en WSViaticos.GetTableroDeControlDePostulaciones(Int32 id_usuario) en c:\Repositorios\Belén\rrhh\WebAsistencia\WSViaticos\App_Code\WSViaticos.cs:línea 2937
   --- Fin del seguimiento de la pila de la excepción interna ---

Server stack trace: 
   en System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   en System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   en System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   en System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   en System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   en System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   en WSViaticos.WSViaticosSoap.GetTableroDeControlDePostulaciones(Int32 id_usuario)
   en WSViaticos.WSViaticosSoapClient.GetTableroDeControlDePostulaciones(Int32 id_usuario) en c:\Users\bcevey\AppData\Local\Temp\Temporary ASP.NET Files\webrh\9fa81700\e8bb1e05\App_WebReferences.yce_w_wd.0.cs:línea 12520
   en FormularioConcursar_TableroControl.Page_Load(Object sender, EventArgs e) en c:\Repositorios\Belén\rrhh\WebAsistencia\WebRH\FormularioConcursar\TableroControl.aspx.cs:línea 21
   en System.Web.Util.CalliHelper.EventArgFunctionCaller(IntPtr fp, Object o, Object t, EventArgs e)
   en System.Web.Util.CalliEventHandlerDelegateProxy.Callback(Object sender, EventArgs e)
   en System.Web.UI.Control.OnLoad(EventArgs e)
   en System.Web.UI.Control.LoadRecursive()
   en System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.HandleError(Exception e)
   en System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.ProcessRequest()
   en System.Web.UI.Page.ProcessRequestWithNoAssert(HttpContext context)
   en System.Web.UI.Page.ProcessRequest(HttpContext context)
   en ASP.formularioconcursar_tablerocontrol_aspx.ProcessRequest(HttpContext context) en c:\Users\bcevey\AppData\Local\Temp\Temporary ASP.NET Files\webrh\9fa81700\e8bb1e05\App_Web_jbicqkul.8.cs:línea 0
   en System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   en System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
26/11/2015 09:20:23 p.m. - ---------------------------------------------
26/11/2015 09:20:23 p.m. - System.Web.HttpUnhandledException (0x80004005): Se produjo una excepción de tipo 'System.Web.HttpUnhandledException'. ---> System.ServiceModel.FaultException: System.Web.Services.Protocols.SoapException: El servidor no puede procesar la solicitud. ---> System.Data.SqlClient.SqlException: Los datos de cadena o binarios se truncarían.
Se terminó la instrucción.
   en General.Repositorios.ConexionBDSQL.Ejecutar(String procedimiento, Dictionary`2 parametros) en C:\Repositorios\Belén\rrhh\ProyectoNet\General\Repositorios\ConexionBDSQL.cs:línea 136
   en General.RepositorioDePostulaciones.TableroDeControlPostulaciones() en C:\Repositorios\Belén\rrhh\ProyectoNet\General\Postular\RepositorioDePostulaciones.cs:línea 377
   en WSViaticos.GetTableroDeControlDePostulaciones(Int32 id_usuario) en c:\Repositorios\Belén\rrhh\WebAsistencia\WSViaticos\App_Code\WSViaticos.cs:línea 2937
   --- Fin del seguimiento de la pila de la excepción interna ---

Server stack trace: 
   en System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   en System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   en System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   en System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   en System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   en System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   en WSViaticos.WSViaticosSoap.GetTableroDeControlDePostulaciones(Int32 id_usuario)
   en WSViaticos.WSViaticosSoapClient.GetTableroDeControlDePostulaciones(Int32 id_usuario) en c:\Users\bcevey\AppData\Local\Temp\Temporary ASP.NET Files\webrh\9fa81700\e8bb1e05\App_WebReferences.yce_w_wd.0.cs:línea 12520
   en FormularioConcursar_TableroControl.Page_Load(Object sender, EventArgs e) en c:\Repositorios\Belén\rrhh\WebAsistencia\WebRH\FormularioConcursar\TableroControl.aspx.cs:línea 21
   en System.Web.Util.CalliHelper.EventArgFunctionCaller(IntPtr fp, Object o, Object t, EventArgs e)
   en System.Web.Util.CalliEventHandlerDelegateProxy.Callback(Object sender, EventArgs e)
   en System.Web.UI.Control.OnLoad(EventArgs e)
   en System.Web.UI.Control.LoadRecursive()
   en System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.HandleError(Exception e)
   en System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.ProcessRequest()
   en System.Web.UI.Page.ProcessRequestWithNoAssert(HttpContext context)
   en System.Web.UI.Page.ProcessRequest(HttpContext context)
   en ASP.formularioconcursar_tablerocontrol_aspx.ProcessRequest(HttpContext context) en c:\Users\bcevey\AppData\Local\Temp\Temporary ASP.NET Files\webrh\9fa81700\e8bb1e05\App_Web_jbicqkul.8.cs:línea 0
   en System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   en System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
