25/11/2016 11:58:48 - ---------------------------------------------
25/11/2016 11:58:48 - System.Web.HttpUnhandledException (0x80004005): Se produjo una excepción de tipo 'System.Web.HttpUnhandledException'. ---> System.TimeoutException: El canal de solicitud agotó el tiempo de espera mientras esperaba una respuesta después de 00:01:00. Aumente el valor de tiempo de espera pasado a la llamada a Request, o bien aumente el valor de SendTimeout en el enlace. El tiempo asignado a esta operación puede haber sido una parte de un tiempo de espera mayor. ---> System.TimeoutException: La solicitud HTTP a 'http://localhost:43412/WSViaticos/WSViaticos.asmx' superó el tiempo de espera asignado de 00:01:00. El tiempo asignado a esta operación puede haber sido una parte de un tiempo de espera mayor. ---> System.Net.WebException: Se excedió el tiempo de espera de la operación
   en System.Net.HttpWebRequest.GetResponse()
   en System.ServiceModel.Channels.HttpChannelFactory.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.ServiceModel.Channels.HttpChannelUtilities.ProcessGetResponseWebException(WebException webException, HttpWebRequest request, HttpAbortReason abortReason)
   en System.ServiceModel.Channels.HttpChannelFactory.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   en System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   --- Fin del seguimiento de la pila de la excepción interna ---

Server stack trace: 
   en System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   en System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   en System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   en System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   en System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   en System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   en System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   en WSViaticos.WSViaticosSoap.RecuperarUsuario(String criterio)
   en WSViaticos.WSViaticosSoapClient.RecuperarUsuario(String criterio) en c:\Users\clurgo\AppData\Local\Temp\Temporary ASP.NET Files\webrh\df8a7146\84c3bc9a\App_WebReferences.cxn5rmtz.0.cs:línea 16901
   en RegistroPostular_FormCaptchaRecupero.btn_recuperar_Click(Object sender, EventArgs e) en c:\Repositorio\Javier\RRHH\WebAsistencia\WebRH\RegistroPostular\FormCaptchaRecupero.aspx.cs:línea 23
   en System.Web.UI.WebControls.Button.OnClick(EventArgs e)
   en System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument)
   en System.Web.UI.WebControls.Button.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument)
   en System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument)
   en System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)
   en System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.HandleError(Exception e)
   en System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.ProcessRequest()
   en System.Web.UI.Page.ProcessRequestWithNoAssert(HttpContext context)
   en System.Web.UI.Page.ProcessRequest(HttpContext context)
   en ASP.registropostular_formcaptcharecupero_aspx.ProcessRequest(HttpContext context) en c:\Users\clurgo\AppData\Local\Temp\Temporary ASP.NET Files\webrh\df8a7146\84c3bc9a\App_Web_l4pmm24f.0.cs:línea 0
   en System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   en System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
25/11/2016 12:06:11 - ---------------------------------------------
25/11/2016 12:06:11 - System.Web.HttpUnhandledException (0x80004005): Se produjo una excepción de tipo 'System.Web.HttpUnhandledException'. ---> System.TimeoutException: El canal de solicitud agotó el tiempo de espera mientras esperaba una respuesta después de 00:01:00. Aumente el valor de tiempo de espera pasado a la llamada a Request, o bien aumente el valor de SendTimeout en el enlace. El tiempo asignado a esta operación puede haber sido una parte de un tiempo de espera mayor. ---> System.TimeoutException: La solicitud HTTP a 'http://localhost:43412/WSViaticos/WSViaticos.asmx' superó el tiempo de espera asignado de 00:01:00. El tiempo asignado a esta operación puede haber sido una parte de un tiempo de espera mayor. ---> System.Net.WebException: Se excedió el tiempo de espera de la operación
   en System.Net.HttpWebRequest.GetResponse()
   en System.ServiceModel.Channels.HttpChannelFactory.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.ServiceModel.Channels.HttpChannelUtilities.ProcessGetResponseWebException(WebException webException, HttpWebRequest request, HttpAbortReason abortReason)
   en System.ServiceModel.Channels.HttpChannelFactory.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   en System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   --- Fin del seguimiento de la pila de la excepción interna ---

Server stack trace: 
   en System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   en System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   en System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   en System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   en System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   en System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   en System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   en WSViaticos.WSViaticosSoap.RecuperarUsuario(String criterio)
   en WSViaticos.WSViaticosSoapClient.RecuperarUsuario(String criterio) en c:\Users\clurgo\AppData\Local\Temp\Temporary ASP.NET Files\webrh\df8a7146\84c3bc9a\App_WebReferences.cxn5rmtz.0.cs:línea 16901
   en RegistroPostular_FormCaptchaRecupero.btn_recuperar_Click(Object sender, EventArgs e) en c:\Repositorio\Javier\RRHH\WebAsistencia\WebRH\RegistroPostular\FormCaptchaRecupero.aspx.cs:línea 23
   en System.Web.UI.WebControls.Button.OnClick(EventArgs e)
   en System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument)
   en System.Web.UI.WebControls.Button.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument)
   en System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument)
   en System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)
   en System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.HandleError(Exception e)
   en System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.ProcessRequest()
   en System.Web.UI.Page.ProcessRequestWithNoAssert(HttpContext context)
   en System.Web.UI.Page.ProcessRequest(HttpContext context)
   en ASP.registropostular_formcaptcharecupero_aspx.ProcessRequest(HttpContext context) en c:\Users\clurgo\AppData\Local\Temp\Temporary ASP.NET Files\webrh\df8a7146\84c3bc9a\App_Web_l4pmm24f.0.cs:línea 0
   en System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   en System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
25/11/2016 12:13:37 - ---------------------------------------------
25/11/2016 12:13:37 - System.Web.HttpUnhandledException (0x80004005): Se produjo una excepción de tipo 'System.Web.HttpUnhandledException'. ---> System.ServiceModel.FaultException: System.Web.Services.Protocols.SoapException: El servidor no puede procesar la solicitud. ---> System.Web.HttpException: Error de transporte en la conexión al servidor.
 ---> System.Reflection.TargetInvocationException: Se produjo una excepción en el destino de la invocación. ---> System.Runtime.InteropServices.COMException: Error de transporte en la conexión al servidor.

   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.RuntimeType.InvokeDispMethod(String name, BindingFlags invokeAttr, Object target, Object[] args, Boolean[] byrefModifiers, Int32 culture, String[] namedParameters)
   en System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   en System.Web.Mail.SmtpMail.LateBoundAccessHelper.CallMethod(Object obj, String methodName, Object[] args)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.Web.Mail.SmtpMail.LateBoundAccessHelper.CallMethod(Object obj, String methodName, Object[] args)
   en System.Web.Mail.SmtpMail.CdoSysHelper.Send(MailMessage message)
   en System.Web.Mail.SmtpMail.Send(MailMessage message)
   en General.MailSender.SendEmail(String pGmailEmail, String pGmailPassword, String pTo, String pSubject, String pBody, MailFormat pFormat, String pAttachmentPath) en C:\Repositorio\Javier\RRHH\ProyectoNet\General\MICOI\MailSender.cs:línea 71
   en General.MAU.Autorizador.EnviarMailDeRecupero(Usuario usuario, String mail) en C:\Repositorio\Javier\RRHH\ProyectoNet\General\MAU\Autorizador.cs:línea 232
   en General.MAU.Autorizador.RecuperarUsuario(String criterio) en C:\Repositorio\Javier\RRHH\ProyectoNet\General\MAU\Autorizador.cs:línea 211
   en WSViaticos.RecuperarUsuario(String criterio) en c:\Repositorio\Javier\RRHH\WebAsistencia\WSViaticos\App_Code\WSViaticos.cs:línea 3168
   --- Fin del seguimiento de la pila de la excepción interna ---

Server stack trace: 
   en System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   en System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   en System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   en System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   en System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   en System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   en WSViaticos.WSViaticosSoap.RecuperarUsuario(String criterio)
   en WSViaticos.WSViaticosSoapClient.RecuperarUsuario(String criterio) en c:\Users\clurgo\AppData\Local\Temp\Temporary ASP.NET Files\webrh\df8a7146\84c3bc9a\App_WebReferences.cxn5rmtz.0.cs:línea 16901
   en RegistroPostular_FormCaptchaRecupero.btn_recuperar_Click(Object sender, EventArgs e) en c:\Repositorio\Javier\RRHH\WebAsistencia\WebRH\RegistroPostular\FormCaptchaRecupero.aspx.cs:línea 23
   en System.Web.UI.WebControls.Button.OnClick(EventArgs e)
   en System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument)
   en System.Web.UI.WebControls.Button.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument)
   en System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument)
   en System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)
   en System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.HandleError(Exception e)
   en System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.ProcessRequest()
   en System.Web.UI.Page.ProcessRequestWithNoAssert(HttpContext context)
   en System.Web.UI.Page.ProcessRequest(HttpContext context)
   en ASP.registropostular_formcaptcharecupero_aspx.ProcessRequest(HttpContext context) en c:\Users\clurgo\AppData\Local\Temp\Temporary ASP.NET Files\webrh\df8a7146\84c3bc9a\App_Web_l4pmm24f.0.cs:línea 0
   en System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   en System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
25/11/2016 12:22:32 - ---------------------------------------------
25/11/2016 12:22:32 - System.Web.HttpUnhandledException (0x80004005): Se produjo una excepción de tipo 'System.Web.HttpUnhandledException'. ---> System.TimeoutException: El canal de solicitud agotó el tiempo de espera mientras esperaba una respuesta después de 00:00:59.9989999. Aumente el valor de tiempo de espera pasado a la llamada a Request, o bien aumente el valor de SendTimeout en el enlace. El tiempo asignado a esta operación puede haber sido una parte de un tiempo de espera mayor. ---> System.TimeoutException: La solicitud HTTP a 'http://localhost:43412/WSViaticos/WSViaticos.asmx' superó el tiempo de espera asignado de 00:01:00. El tiempo asignado a esta operación puede haber sido una parte de un tiempo de espera mayor. ---> System.Net.WebException: Se excedió el tiempo de espera de la operación
   en System.Net.HttpWebRequest.GetResponse()
   en System.ServiceModel.Channels.HttpChannelFactory.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.ServiceModel.Channels.HttpChannelUtilities.ProcessGetResponseWebException(WebException webException, HttpWebRequest request, HttpAbortReason abortReason)
   en System.ServiceModel.Channels.HttpChannelFactory.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   en System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   --- Fin del seguimiento de la pila de la excepción interna ---

Server stack trace: 
   en System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   en System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   en System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   en System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   en System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   en System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   en System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   en WSViaticos.WSViaticosSoap.RecuperarUsuario(String criterio)
   en WSViaticos.WSViaticosSoapClient.RecuperarUsuario(String criterio) en c:\Users\clurgo\AppData\Local\Temp\Temporary ASP.NET Files\webrh\df8a7146\84c3bc9a\App_WebReferences.cxn5rmtz.0.cs:línea 16901
   en RegistroPostular_FormCaptchaRecupero.btn_recuperar_Click(Object sender, EventArgs e) en c:\Repositorio\Javier\RRHH\WebAsistencia\WebRH\RegistroPostular\FormCaptchaRecupero.aspx.cs:línea 23
   en System.Web.UI.WebControls.Button.OnClick(EventArgs e)
   en System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument)
   en System.Web.UI.WebControls.Button.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument)
   en System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument)
   en System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)
   en System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.HandleError(Exception e)
   en System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.ProcessRequest()
   en System.Web.UI.Page.ProcessRequestWithNoAssert(HttpContext context)
   en System.Web.UI.Page.ProcessRequest(HttpContext context)
   en ASP.registropostular_formcaptcharecupero_aspx.ProcessRequest(HttpContext context) en c:\Users\clurgo\AppData\Local\Temp\Temporary ASP.NET Files\webrh\df8a7146\84c3bc9a\App_Web_l4pmm24f.0.cs:línea 0
   en System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   en System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
25/11/2016 12:26:49 - ---------------------------------------------
25/11/2016 12:26:49 - System.Web.HttpUnhandledException (0x80004005): Se produjo una excepción de tipo 'System.Web.HttpUnhandledException'. ---> System.TimeoutException: El canal de solicitud agotó el tiempo de espera mientras esperaba una respuesta después de 00:01:00. Aumente el valor de tiempo de espera pasado a la llamada a Request, o bien aumente el valor de SendTimeout en el enlace. El tiempo asignado a esta operación puede haber sido una parte de un tiempo de espera mayor. ---> System.TimeoutException: La solicitud HTTP a 'http://localhost:43412/WSViaticos/WSViaticos.asmx' superó el tiempo de espera asignado de 00:01:00. El tiempo asignado a esta operación puede haber sido una parte de un tiempo de espera mayor. ---> System.Net.WebException: Anulada la solicitud: Se excedió el tiempo de espera de la operación.
   en System.Net.HttpWebRequest.GetResponse()
   en System.ServiceModel.Channels.HttpChannelFactory.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.ServiceModel.Channels.HttpChannelUtilities.ProcessGetResponseWebException(WebException webException, HttpWebRequest request, HttpAbortReason abortReason)
   en System.ServiceModel.Channels.HttpChannelFactory.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   en System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   --- Fin del seguimiento de la pila de la excepción interna ---

Server stack trace: 
   en System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   en System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   en System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   en System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   en System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   en System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   en System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   en WSViaticos.WSViaticosSoap.RecuperarUsuario(String criterio)
   en WSViaticos.WSViaticosSoapClient.RecuperarUsuario(String criterio) en c:\Users\clurgo\AppData\Local\Temp\Temporary ASP.NET Files\webrh\df8a7146\84c3bc9a\App_WebReferences.cxn5rmtz.0.cs:línea 16901
   en RegistroPostular_FormCaptchaRecupero.btn_recuperar_Click(Object sender, EventArgs e) en c:\Repositorio\Javier\RRHH\WebAsistencia\WebRH\RegistroPostular\FormCaptchaRecupero.aspx.cs:línea 23
   en System.Web.UI.WebControls.Button.OnClick(EventArgs e)
   en System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument)
   en System.Web.UI.WebControls.Button.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument)
   en System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument)
   en System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)
   en System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.HandleError(Exception e)
   en System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.ProcessRequest()
   en System.Web.UI.Page.ProcessRequestWithNoAssert(HttpContext context)
   en System.Web.UI.Page.ProcessRequest(HttpContext context)
   en ASP.registropostular_formcaptcharecupero_aspx.ProcessRequest(HttpContext context) en c:\Users\clurgo\AppData\Local\Temp\Temporary ASP.NET Files\webrh\df8a7146\84c3bc9a\App_Web_l4pmm24f.0.cs:línea 0
   en System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   en System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
25/11/2016 12:29:44 - ---------------------------------------------
25/11/2016 12:29:44 - System.Web.HttpUnhandledException (0x80004005): Se produjo una excepción de tipo 'System.Web.HttpUnhandledException'. ---> System.TimeoutException: El canal de solicitud agotó el tiempo de espera mientras esperaba una respuesta después de 00:00:59.9990000. Aumente el valor de tiempo de espera pasado a la llamada a Request, o bien aumente el valor de SendTimeout en el enlace. El tiempo asignado a esta operación puede haber sido una parte de un tiempo de espera mayor. ---> System.TimeoutException: La solicitud HTTP a 'http://localhost:43412/WSViaticos/WSViaticos.asmx' superó el tiempo de espera asignado de 00:01:00. El tiempo asignado a esta operación puede haber sido una parte de un tiempo de espera mayor. ---> System.Net.WebException: Se excedió el tiempo de espera de la operación
   en System.Net.HttpWebRequest.GetResponse()
   en System.ServiceModel.Channels.HttpChannelFactory.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.ServiceModel.Channels.HttpChannelUtilities.ProcessGetResponseWebException(WebException webException, HttpWebRequest request, HttpAbortReason abortReason)
   en System.ServiceModel.Channels.HttpChannelFactory.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   en System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   --- Fin del seguimiento de la pila de la excepción interna ---

Server stack trace: 
   en System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   en System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   en System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   en System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   en System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   en System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   en System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   en WSViaticos.WSViaticosSoap.RecuperarUsuario(String criterio)
   en WSViaticos.WSViaticosSoapClient.RecuperarUsuario(String criterio) en c:\Users\clurgo\AppData\Local\Temp\Temporary ASP.NET Files\webrh\df8a7146\84c3bc9a\App_WebReferences.cxn5rmtz.0.cs:línea 16901
   en RegistroPostular_FormCaptchaRecupero.btn_recuperar_Click(Object sender, EventArgs e) en c:\Repositorio\Javier\RRHH\WebAsistencia\WebRH\RegistroPostular\FormCaptchaRecupero.aspx.cs:línea 23
   en System.Web.UI.WebControls.Button.OnClick(EventArgs e)
   en System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument)
   en System.Web.UI.WebControls.Button.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument)
   en System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument)
   en System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)
   en System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.HandleError(Exception e)
   en System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.ProcessRequest()
   en System.Web.UI.Page.ProcessRequestWithNoAssert(HttpContext context)
   en System.Web.UI.Page.ProcessRequest(HttpContext context)
   en ASP.registropostular_formcaptcharecupero_aspx.ProcessRequest(HttpContext context) en c:\Users\clurgo\AppData\Local\Temp\Temporary ASP.NET Files\webrh\df8a7146\84c3bc9a\App_Web_l4pmm24f.0.cs:línea 0
   en System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   en System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
25/11/2016 13:02:50 - ---------------------------------------------
25/11/2016 13:02:50 - System.Web.HttpUnhandledException (0x80004005): Se produjo una excepción de tipo 'System.Web.HttpUnhandledException'. ---> System.TimeoutException: El canal de solicitud agotó el tiempo de espera mientras esperaba una respuesta después de 00:01:00. Aumente el valor de tiempo de espera pasado a la llamada a Request, o bien aumente el valor de SendTimeout en el enlace. El tiempo asignado a esta operación puede haber sido una parte de un tiempo de espera mayor. ---> System.TimeoutException: La solicitud HTTP a 'http://localhost:43412/WSViaticos/WSViaticos.asmx' superó el tiempo de espera asignado de 00:01:00. El tiempo asignado a esta operación puede haber sido una parte de un tiempo de espera mayor. ---> System.Net.WebException: Se excedió el tiempo de espera de la operación
   en System.Net.HttpWebRequest.GetResponse()
   en System.ServiceModel.Channels.HttpChannelFactory.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.ServiceModel.Channels.HttpChannelUtilities.ProcessGetResponseWebException(WebException webException, HttpWebRequest request, HttpAbortReason abortReason)
   en System.ServiceModel.Channels.HttpChannelFactory.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   en System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   --- Fin del seguimiento de la pila de la excepción interna ---

Server stack trace: 
   en System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   en System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   en System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   en System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   en System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   en System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   en System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   en WSViaticos.WSViaticosSoap.RecuperarUsuario(String criterio)
   en WSViaticos.WSViaticosSoapClient.RecuperarUsuario(String criterio) en c:\Users\clurgo\AppData\Local\Temp\Temporary ASP.NET Files\webrh\df8a7146\84c3bc9a\App_WebReferences.cxn5rmtz.0.cs:línea 16901
   en RegistroPostular_FormCaptchaRecupero.btn_recuperar_Click(Object sender, EventArgs e) en c:\Repositorio\Javier\RRHH\WebAsistencia\WebRH\RegistroPostular\FormCaptchaRecupero.aspx.cs:línea 23
   en System.Web.UI.WebControls.Button.OnClick(EventArgs e)
   en System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument)
   en System.Web.UI.WebControls.Button.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument)
   en System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument)
   en System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)
   en System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.HandleError(Exception e)
   en System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.ProcessRequest()
   en System.Web.UI.Page.ProcessRequestWithNoAssert(HttpContext context)
   en System.Web.UI.Page.ProcessRequest(HttpContext context)
   en ASP.registropostular_formcaptcharecupero_aspx.ProcessRequest(HttpContext context) en c:\Users\clurgo\AppData\Local\Temp\Temporary ASP.NET Files\webrh\df8a7146\84c3bc9a\App_Web_l4pmm24f.0.cs:línea 0
   en System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   en System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
25/11/2016 13:05:05 - ---------------------------------------------
25/11/2016 13:05:05 - System.Web.HttpUnhandledException (0x80004005): Se produjo una excepción de tipo 'System.Web.HttpUnhandledException'. ---> System.ServiceModel.FaultException: System.Web.Services.Protocols.SoapException: El servidor no puede procesar la solicitud. ---> System.Exception: No se pudo enviar un mail con la clave
   en General.MAU.Autorizador.<EnviarMail>b__13() en C:\Repositorio\Javier\RRHH\ProyectoNet\General\MAU\Autorizador.cs:línea 244
   en General.EnviadorDeMails.EnviarMail(NetworkCredential cred, String to, String asunto, String cuerpo, Action on_success, Action on_error) en C:\Repositorio\Javier\RRHH\ProyectoNet\General\MICOI\EnviadorDeMails.cs:línea 33
   en General.MAU.Autorizador.EnviarMail(String mail, String titulo, String cuerpo) en C:\Repositorio\Javier\RRHH\ProyectoNet\General\MAU\Autorizador.cs:línea 239
   en General.MAU.Autorizador.EnviarMailDeRecupero(Usuario usuario, String mail) en C:\Repositorio\Javier\RRHH\ProyectoNet\General\MAU\Autorizador.cs:línea 231
   en General.MAU.Autorizador.RecuperarUsuario(String criterio) en C:\Repositorio\Javier\RRHH\ProyectoNet\General\MAU\Autorizador.cs:línea 211
   en WSViaticos.RecuperarUsuario(String criterio) en c:\Repositorio\Javier\RRHH\WebAsistencia\WSViaticos\App_Code\WSViaticos.cs:línea 3168
   --- Fin del seguimiento de la pila de la excepción interna ---

Server stack trace: 
   en System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   en System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   en System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   en System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   en System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   en System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   en WSViaticos.WSViaticosSoap.RecuperarUsuario(String criterio)
   en WSViaticos.WSViaticosSoapClient.RecuperarUsuario(String criterio) en c:\Users\clurgo\AppData\Local\Temp\Temporary ASP.NET Files\webrh\df8a7146\84c3bc9a\App_WebReferences.cxn5rmtz.0.cs:línea 16901
   en RegistroPostular_FormCaptchaRecupero.btn_recuperar_Click(Object sender, EventArgs e) en c:\Repositorio\Javier\RRHH\WebAsistencia\WebRH\RegistroPostular\FormCaptchaRecupero.aspx.cs:línea 23
   en System.Web.UI.WebControls.Button.OnClick(EventArgs e)
   en System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument)
   en System.Web.UI.WebControls.Button.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument)
   en System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument)
   en System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)
   en System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.HandleError(Exception e)
   en System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.ProcessRequest()
   en System.Web.UI.Page.ProcessRequestWithNoAssert(HttpContext context)
   en System.Web.UI.Page.ProcessRequest(HttpContext context)
   en ASP.registropostular_formcaptcharecupero_aspx.ProcessRequest(HttpContext context) en c:\Users\clurgo\AppData\Local\Temp\Temporary ASP.NET Files\webrh\df8a7146\84c3bc9a\App_Web_l4pmm24f.0.cs:línea 0
   en System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   en System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
25/11/2016 13:07:31 - ---------------------------------------------
25/11/2016 13:07:31 - System.Web.HttpUnhandledException (0x80004005): Se produjo una excepción de tipo 'System.Web.HttpUnhandledException'. ---> System.ServiceModel.FaultException: System.Web.Services.Protocols.SoapException: El servidor no puede procesar la solicitud. ---> System.Exception: No se pudo enviar un mail con la clave
   en General.MAU.Autorizador.<EnviarMail>b__13() en C:\Repositorio\Javier\RRHH\ProyectoNet\General\MAU\Autorizador.cs:línea 244
   en General.EnviadorDeMails.EnviarMail(NetworkCredential cred, String to, String asunto, String cuerpo, Action on_success, Action on_error) en C:\Repositorio\Javier\RRHH\ProyectoNet\General\MICOI\EnviadorDeMails.cs:línea 33
   en General.MAU.Autorizador.EnviarMail(String mail, String titulo, String cuerpo) en C:\Repositorio\Javier\RRHH\ProyectoNet\General\MAU\Autorizador.cs:línea 239
   en General.MAU.Autorizador.EnviarMailDeRecupero(Usuario usuario, String mail) en C:\Repositorio\Javier\RRHH\ProyectoNet\General\MAU\Autorizador.cs:línea 231
   en General.MAU.Autorizador.RecuperarUsuario(String criterio) en C:\Repositorio\Javier\RRHH\ProyectoNet\General\MAU\Autorizador.cs:línea 211
   en WSViaticos.RecuperarUsuario(String criterio) en c:\Repositorio\Javier\RRHH\WebAsistencia\WSViaticos\App_Code\WSViaticos.cs:línea 3168
   --- Fin del seguimiento de la pila de la excepción interna ---

Server stack trace: 
   en System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   en System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   en System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   en System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   en System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   en System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   en WSViaticos.WSViaticosSoap.RecuperarUsuario(String criterio)
   en WSViaticos.WSViaticosSoapClient.RecuperarUsuario(String criterio) en c:\Users\clurgo\AppData\Local\Temp\Temporary ASP.NET Files\webrh\df8a7146\84c3bc9a\App_WebReferences.cxn5rmtz.0.cs:línea 16901
   en RegistroPostular_FormCaptchaRecupero.btn_recuperar_Click(Object sender, EventArgs e) en c:\Repositorio\Javier\RRHH\WebAsistencia\WebRH\RegistroPostular\FormCaptchaRecupero.aspx.cs:línea 23
   en System.Web.UI.WebControls.Button.OnClick(EventArgs e)
   en System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument)
   en System.Web.UI.WebControls.Button.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument)
   en System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument)
   en System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)
   en System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.HandleError(Exception e)
   en System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.ProcessRequest()
   en System.Web.UI.Page.ProcessRequestWithNoAssert(HttpContext context)
   en System.Web.UI.Page.ProcessRequest(HttpContext context)
   en ASP.registropostular_formcaptcharecupero_aspx.ProcessRequest(HttpContext context) en c:\Users\clurgo\AppData\Local\Temp\Temporary ASP.NET Files\webrh\df8a7146\84c3bc9a\App_Web_l4pmm24f.0.cs:línea 0
   en System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   en System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
25/11/2016 13:41:59 - ---------------------------------------------
25/11/2016 13:41:59 - System.Web.HttpUnhandledException (0x80004005): Se produjo una excepción de tipo 'System.Web.HttpUnhandledException'. ---> System.TimeoutException: El canal de solicitud agotó el tiempo de espera mientras esperaba una respuesta después de 00:00:59.9990000. Aumente el valor de tiempo de espera pasado a la llamada a Request, o bien aumente el valor de SendTimeout en el enlace. El tiempo asignado a esta operación puede haber sido una parte de un tiempo de espera mayor. ---> System.TimeoutException: La solicitud HTTP a 'http://localhost:43412/WSViaticos/WSViaticos.asmx' superó el tiempo de espera asignado de 00:01:00. El tiempo asignado a esta operación puede haber sido una parte de un tiempo de espera mayor. ---> System.Net.WebException: Se excedió el tiempo de espera de la operación
   en System.Net.HttpWebRequest.GetResponse()
   en System.ServiceModel.Channels.HttpChannelFactory.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.ServiceModel.Channels.HttpChannelUtilities.ProcessGetResponseWebException(WebException webException, HttpWebRequest request, HttpAbortReason abortReason)
   en System.ServiceModel.Channels.HttpChannelFactory.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   en System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   --- Fin del seguimiento de la pila de la excepción interna ---

Server stack trace: 
   en System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   en System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   en System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   en System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   en System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   en System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   en System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   en WSViaticos.WSViaticosSoap.RecuperarUsuario(String criterio)
   en WSViaticos.WSViaticosSoapClient.RecuperarUsuario(String criterio) en c:\Users\clurgo\AppData\Local\Temp\Temporary ASP.NET Files\webrh\df8a7146\84c3bc9a\App_WebReferences.cxn5rmtz.0.cs:línea 16901
   en RegistroPostular_FormCaptchaRecupero.btn_recuperar_Click(Object sender, EventArgs e) en c:\Repositorio\Javier\RRHH\WebAsistencia\WebRH\RegistroPostular\FormCaptchaRecupero.aspx.cs:línea 23
   en System.Web.UI.WebControls.Button.OnClick(EventArgs e)
   en System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument)
   en System.Web.UI.WebControls.Button.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument)
   en System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument)
   en System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)
   en System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.HandleError(Exception e)
   en System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.ProcessRequest()
   en System.Web.UI.Page.ProcessRequestWithNoAssert(HttpContext context)
   en System.Web.UI.Page.ProcessRequest(HttpContext context)
   en ASP.registropostular_formcaptcharecupero_aspx.ProcessRequest(HttpContext context) en c:\Users\clurgo\AppData\Local\Temp\Temporary ASP.NET Files\webrh\df8a7146\84c3bc9a\App_Web_l4pmm24f.0.cs:línea 0
   en System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   en System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
25/11/2016 13:42:51 - ---------------------------------------------
25/11/2016 13:42:51 - System.Web.HttpUnhandledException (0x80004005): Se produjo una excepción de tipo 'System.Web.HttpUnhandledException'. ---> System.ServiceModel.FaultException: System.Web.Services.Protocols.SoapException: El servidor no puede procesar la solicitud. ---> System.Exception: No se pudo enviar un mail con la clave
   en General.MAU.Autorizador.<EnviarMail>b__13() en C:\Repositorio\Javier\RRHH\ProyectoNet\General\MAU\Autorizador.cs:línea 244
   en General.EnviadorDeMails.EnviarMail(NetworkCredential cred, String to, String asunto, String cuerpo, Action on_success, Action on_error) en C:\Repositorio\Javier\RRHH\ProyectoNet\General\MICOI\EnviadorDeMails.cs:línea 33
   en General.MAU.Autorizador.EnviarMail(String mail, String titulo, String cuerpo) en C:\Repositorio\Javier\RRHH\ProyectoNet\General\MAU\Autorizador.cs:línea 239
   en General.MAU.Autorizador.EnviarMailDeRecupero(Usuario usuario, String mail) en C:\Repositorio\Javier\RRHH\ProyectoNet\General\MAU\Autorizador.cs:línea 231
   en General.MAU.Autorizador.RecuperarUsuario(String criterio) en C:\Repositorio\Javier\RRHH\ProyectoNet\General\MAU\Autorizador.cs:línea 211
   en WSViaticos.RecuperarUsuario(String criterio) en c:\Repositorio\Javier\RRHH\WebAsistencia\WSViaticos\App_Code\WSViaticos.cs:línea 3168
   --- Fin del seguimiento de la pila de la excepción interna ---

Server stack trace: 
   en System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   en System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   en System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   en System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   en System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   en System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   en WSViaticos.WSViaticosSoap.RecuperarUsuario(String criterio)
   en WSViaticos.WSViaticosSoapClient.RecuperarUsuario(String criterio) en c:\Users\clurgo\AppData\Local\Temp\Temporary ASP.NET Files\webrh\df8a7146\84c3bc9a\App_WebReferences.cxn5rmtz.0.cs:línea 16901
   en RegistroPostular_FormCaptchaRecupero.btn_recuperar_Click(Object sender, EventArgs e) en c:\Repositorio\Javier\RRHH\WebAsistencia\WebRH\RegistroPostular\FormCaptchaRecupero.aspx.cs:línea 23
   en System.Web.UI.WebControls.Button.OnClick(EventArgs e)
   en System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument)
   en System.Web.UI.WebControls.Button.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument)
   en System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument)
   en System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)
   en System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.HandleError(Exception e)
   en System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.ProcessRequest()
   en System.Web.UI.Page.ProcessRequestWithNoAssert(HttpContext context)
   en System.Web.UI.Page.ProcessRequest(HttpContext context)
   en ASP.registropostular_formcaptcharecupero_aspx.ProcessRequest(HttpContext context) en c:\Users\clurgo\AppData\Local\Temp\Temporary ASP.NET Files\webrh\df8a7146\84c3bc9a\App_Web_l4pmm24f.0.cs:línea 0
   en System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   en System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
25/11/2016 13:44:53 - ---------------------------------------------
25/11/2016 13:44:53 - System.Web.HttpUnhandledException (0x80004005): Se produjo una excepción de tipo 'System.Web.HttpUnhandledException'. ---> System.ServiceModel.FaultException: System.Web.Services.Protocols.SoapException: El servidor no puede procesar la solicitud. ---> System.Exception: No se pudo enviar un mail con la clave
   en General.MAU.Autorizador.<EnviarMail>b__13() en C:\Repositorio\Javier\RRHH\ProyectoNet\General\MAU\Autorizador.cs:línea 244
   en General.EnviadorDeMails.EnviarMail(NetworkCredential cred, String to, String asunto, String cuerpo, Action on_success, Action on_error) en C:\Repositorio\Javier\RRHH\ProyectoNet\General\MICOI\EnviadorDeMails.cs:línea 33
   en General.MAU.Autorizador.EnviarMail(String mail, String titulo, String cuerpo) en C:\Repositorio\Javier\RRHH\ProyectoNet\General\MAU\Autorizador.cs:línea 239
   en General.MAU.Autorizador.EnviarMailDeRecupero(Usuario usuario, String mail) en C:\Repositorio\Javier\RRHH\ProyectoNet\General\MAU\Autorizador.cs:línea 231
   en General.MAU.Autorizador.RecuperarUsuario(String criterio) en C:\Repositorio\Javier\RRHH\ProyectoNet\General\MAU\Autorizador.cs:línea 211
   en WSViaticos.RecuperarUsuario(String criterio) en c:\Repositorio\Javier\RRHH\WebAsistencia\WSViaticos\App_Code\WSViaticos.cs:línea 3168
   --- Fin del seguimiento de la pila de la excepción interna ---

Server stack trace: 
   en System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   en System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   en System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   en System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   en System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   en System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   en WSViaticos.WSViaticosSoap.RecuperarUsuario(String criterio)
   en WSViaticos.WSViaticosSoapClient.RecuperarUsuario(String criterio) en c:\Users\clurgo\AppData\Local\Temp\Temporary ASP.NET Files\webrh\df8a7146\84c3bc9a\App_WebReferences.cxn5rmtz.0.cs:línea 16901
   en RegistroPostular_FormCaptchaRecupero.btn_recuperar_Click(Object sender, EventArgs e) en c:\Repositorio\Javier\RRHH\WebAsistencia\WebRH\RegistroPostular\FormCaptchaRecupero.aspx.cs:línea 23
   en System.Web.UI.WebControls.Button.OnClick(EventArgs e)
   en System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument)
   en System.Web.UI.WebControls.Button.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument)
   en System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument)
   en System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)
   en System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.HandleError(Exception e)
   en System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.ProcessRequest()
   en System.Web.UI.Page.ProcessRequestWithNoAssert(HttpContext context)
   en System.Web.UI.Page.ProcessRequest(HttpContext context)
   en ASP.registropostular_formcaptcharecupero_aspx.ProcessRequest(HttpContext context) en c:\Users\clurgo\AppData\Local\Temp\Temporary ASP.NET Files\webrh\df8a7146\84c3bc9a\App_Web_l4pmm24f.0.cs:línea 0
   en System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   en System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
25/11/2016 13:46:21 - ---------------------------------------------
25/11/2016 13:46:21 - System.Web.HttpUnhandledException (0x80004005): Se produjo una excepción de tipo 'System.Web.HttpUnhandledException'. ---> System.ServiceModel.FaultException: System.Web.Services.Protocols.SoapException: El servidor no puede procesar la solicitud. ---> System.Exception: No se pudo enviar un mail con la clave
   en General.MAU.Autorizador.<EnviarMail>b__13() en C:\Repositorio\Javier\RRHH\ProyectoNet\General\MAU\Autorizador.cs:línea 244
   en General.EnviadorDeMails.EnviarMail(NetworkCredential cred, String to, String asunto, String cuerpo, Action on_success, Action on_error) en C:\Repositorio\Javier\RRHH\ProyectoNet\General\MICOI\EnviadorDeMails.cs:línea 33
   en General.MAU.Autorizador.EnviarMail(String mail, String titulo, String cuerpo) en C:\Repositorio\Javier\RRHH\ProyectoNet\General\MAU\Autorizador.cs:línea 239
   en General.MAU.Autorizador.EnviarMailDeRecupero(Usuario usuario, String mail) en C:\Repositorio\Javier\RRHH\ProyectoNet\General\MAU\Autorizador.cs:línea 231
   en General.MAU.Autorizador.RecuperarUsuario(String criterio) en C:\Repositorio\Javier\RRHH\ProyectoNet\General\MAU\Autorizador.cs:línea 211
   en WSViaticos.RecuperarUsuario(String criterio) en c:\Repositorio\Javier\RRHH\WebAsistencia\WSViaticos\App_Code\WSViaticos.cs:línea 3168
   --- Fin del seguimiento de la pila de la excepción interna ---

Server stack trace: 
   en System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   en System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   en System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   en System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   en System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   en System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   en WSViaticos.WSViaticosSoap.RecuperarUsuario(String criterio)
   en WSViaticos.WSViaticosSoapClient.RecuperarUsuario(String criterio) en c:\Users\clurgo\AppData\Local\Temp\Temporary ASP.NET Files\webrh\df8a7146\84c3bc9a\App_WebReferences.cxn5rmtz.0.cs:línea 16901
   en RegistroPostular_FormCaptchaRecupero.btn_recuperar_Click(Object sender, EventArgs e) en c:\Repositorio\Javier\RRHH\WebAsistencia\WebRH\RegistroPostular\FormCaptchaRecupero.aspx.cs:línea 23
   en System.Web.UI.WebControls.Button.OnClick(EventArgs e)
   en System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument)
   en System.Web.UI.WebControls.Button.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument)
   en System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument)
   en System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)
   en System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.HandleError(Exception e)
   en System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.ProcessRequest()
   en System.Web.UI.Page.ProcessRequestWithNoAssert(HttpContext context)
   en System.Web.UI.Page.ProcessRequest(HttpContext context)
   en ASP.registropostular_formcaptcharecupero_aspx.ProcessRequest(HttpContext context) en c:\Users\clurgo\AppData\Local\Temp\Temporary ASP.NET Files\webrh\df8a7146\84c3bc9a\App_Web_l4pmm24f.0.cs:línea 0
   en System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   en System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
25/11/2016 13:47:29 - ---------------------------------------------
25/11/2016 13:47:29 - System.Web.HttpUnhandledException (0x80004005): Se produjo una excepción de tipo 'System.Web.HttpUnhandledException'. ---> System.ServiceModel.FaultException: System.Web.Services.Protocols.SoapException: El servidor no puede procesar la solicitud. ---> System.Exception: No se pudo enviar un mail con la clave
   en General.MAU.Autorizador.<EnviarMail>b__13() en C:\Repositorio\Javier\RRHH\ProyectoNet\General\MAU\Autorizador.cs:línea 244
   en General.EnviadorDeMails.EnviarMail(NetworkCredential cred, String to, String asunto, String cuerpo, Action on_success, Action on_error) en C:\Repositorio\Javier\RRHH\ProyectoNet\General\MICOI\EnviadorDeMails.cs:línea 33
   en General.MAU.Autorizador.EnviarMail(String mail, String titulo, String cuerpo) en C:\Repositorio\Javier\RRHH\ProyectoNet\General\MAU\Autorizador.cs:línea 239
   en General.MAU.Autorizador.EnviarMailDeRecupero(Usuario usuario, String mail) en C:\Repositorio\Javier\RRHH\ProyectoNet\General\MAU\Autorizador.cs:línea 231
   en General.MAU.Autorizador.RecuperarUsuario(String criterio) en C:\Repositorio\Javier\RRHH\ProyectoNet\General\MAU\Autorizador.cs:línea 211
   en WSViaticos.RecuperarUsuario(String criterio) en c:\Repositorio\Javier\RRHH\WebAsistencia\WSViaticos\App_Code\WSViaticos.cs:línea 3168
   --- Fin del seguimiento de la pila de la excepción interna ---

Server stack trace: 
   en System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   en System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   en System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   en System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   en System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   en System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   en WSViaticos.WSViaticosSoap.RecuperarUsuario(String criterio)
   en WSViaticos.WSViaticosSoapClient.RecuperarUsuario(String criterio) en c:\Users\clurgo\AppData\Local\Temp\Temporary ASP.NET Files\webrh\df8a7146\84c3bc9a\App_WebReferences.cxn5rmtz.0.cs:línea 16901
   en RegistroPostular_FormCaptchaRecupero.btn_recuperar_Click(Object sender, EventArgs e) en c:\Repositorio\Javier\RRHH\WebAsistencia\WebRH\RegistroPostular\FormCaptchaRecupero.aspx.cs:línea 23
   en System.Web.UI.WebControls.Button.OnClick(EventArgs e)
   en System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument)
   en System.Web.UI.WebControls.Button.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument)
   en System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument)
   en System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)
   en System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.HandleError(Exception e)
   en System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.ProcessRequest()
   en System.Web.UI.Page.ProcessRequestWithNoAssert(HttpContext context)
   en System.Web.UI.Page.ProcessRequest(HttpContext context)
   en ASP.registropostular_formcaptcharecupero_aspx.ProcessRequest(HttpContext context) en c:\Users\clurgo\AppData\Local\Temp\Temporary ASP.NET Files\webrh\df8a7146\84c3bc9a\App_Web_l4pmm24f.0.cs:línea 0
   en System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   en System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
25/11/2016 13:51:41 - ---------------------------------------------
25/11/2016 13:51:41 - System.Web.HttpUnhandledException (0x80004005): Se produjo una excepción de tipo 'System.Web.HttpUnhandledException'. ---> System.TimeoutException: El canal de solicitud agotó el tiempo de espera mientras esperaba una respuesta después de 00:00:59.9989999. Aumente el valor de tiempo de espera pasado a la llamada a Request, o bien aumente el valor de SendTimeout en el enlace. El tiempo asignado a esta operación puede haber sido una parte de un tiempo de espera mayor. ---> System.TimeoutException: La solicitud HTTP a 'http://localhost:43412/WSViaticos/WSViaticos.asmx' superó el tiempo de espera asignado de 00:01:00. El tiempo asignado a esta operación puede haber sido una parte de un tiempo de espera mayor. ---> System.Net.WebException: Se excedió el tiempo de espera de la operación
   en System.Net.HttpWebRequest.GetResponse()
   en System.ServiceModel.Channels.HttpChannelFactory.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.ServiceModel.Channels.HttpChannelUtilities.ProcessGetResponseWebException(WebException webException, HttpWebRequest request, HttpAbortReason abortReason)
   en System.ServiceModel.Channels.HttpChannelFactory.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   en System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   --- Fin del seguimiento de la pila de la excepción interna ---

Server stack trace: 
   en System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   en System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   en System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   en System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   en System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   en System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   en System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   en WSViaticos.WSViaticosSoap.RecuperarUsuario(String criterio)
   en WSViaticos.WSViaticosSoapClient.RecuperarUsuario(String criterio) en c:\Users\clurgo\AppData\Local\Temp\Temporary ASP.NET Files\webrh\df8a7146\84c3bc9a\App_WebReferences.cxn5rmtz.0.cs:línea 16901
   en RegistroPostular_FormCaptchaRecupero.btn_recuperar_Click(Object sender, EventArgs e) en c:\Repositorio\Javier\RRHH\WebAsistencia\WebRH\RegistroPostular\FormCaptchaRecupero.aspx.cs:línea 23
   en System.Web.UI.WebControls.Button.OnClick(EventArgs e)
   en System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument)
   en System.Web.UI.WebControls.Button.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument)
   en System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument)
   en System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)
   en System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.HandleError(Exception e)
   en System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.ProcessRequest()
   en System.Web.UI.Page.ProcessRequestWithNoAssert(HttpContext context)
   en System.Web.UI.Page.ProcessRequest(HttpContext context)
   en ASP.registropostular_formcaptcharecupero_aspx.ProcessRequest(HttpContext context) en c:\Users\clurgo\AppData\Local\Temp\Temporary ASP.NET Files\webrh\df8a7146\84c3bc9a\App_Web_l4pmm24f.0.cs:línea 0
   en System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   en System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
25/11/2016 14:09:23 - ---------------------------------------------
25/11/2016 14:09:23 - System.Web.HttpUnhandledException (0x80004005): Se produjo una excepción de tipo 'System.Web.HttpUnhandledException'. ---> System.ServiceModel.FaultException: System.Web.Services.Protocols.SoapException: El servidor no puede procesar la solicitud. ---> System.Exception: No se pudo enviar un mail con la clave
   en General.MAU.Autorizador.<EnviarMail>b__13() en C:\Repositorio\Javier\RRHH\ProyectoNet\General\MAU\Autorizador.cs:línea 244
   en General.EnviadorDeMails.EnviarMail(NetworkCredential cred, String to, String asunto, String cuerpo, Action on_success, Action on_error) en C:\Repositorio\Javier\RRHH\ProyectoNet\General\MICOI\EnviadorDeMails.cs:línea 33
   en General.MAU.Autorizador.EnviarMail(String mail, String titulo, String cuerpo) en C:\Repositorio\Javier\RRHH\ProyectoNet\General\MAU\Autorizador.cs:línea 239
   en General.MAU.Autorizador.EnviarMailDeRecupero(Usuario usuario, String mail) en C:\Repositorio\Javier\RRHH\ProyectoNet\General\MAU\Autorizador.cs:línea 231
   en General.MAU.Autorizador.RecuperarUsuario(String criterio) en C:\Repositorio\Javier\RRHH\ProyectoNet\General\MAU\Autorizador.cs:línea 211
   en WSViaticos.RecuperarUsuario(String criterio) en c:\Repositorio\Javier\RRHH\WebAsistencia\WSViaticos\App_Code\WSViaticos.cs:línea 3168
   --- Fin del seguimiento de la pila de la excepción interna ---

Server stack trace: 
   en System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   en System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   en System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   en System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   en System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   en System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   en WSViaticos.WSViaticosSoap.RecuperarUsuario(String criterio)
   en WSViaticos.WSViaticosSoapClient.RecuperarUsuario(String criterio) en c:\Users\clurgo\AppData\Local\Temp\Temporary ASP.NET Files\webrh\df8a7146\84c3bc9a\App_WebReferences.coylkt6b.0.cs:línea 16901
   en RegistroPostular_FormCaptchaRecupero.btn_recuperar_Click(Object sender, EventArgs e) en c:\Repositorio\Javier\RRHH\WebAsistencia\WebRH\RegistroPostular\FormCaptchaRecupero.aspx.cs:línea 23
   en System.Web.UI.WebControls.Button.OnClick(EventArgs e)
   en System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument)
   en System.Web.UI.WebControls.Button.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument)
   en System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument)
   en System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)
   en System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.HandleError(Exception e)
   en System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   en System.Web.UI.Page.ProcessRequest()
   en System.Web.UI.Page.ProcessRequestWithNoAssert(HttpContext context)
   en System.Web.UI.Page.ProcessRequest(HttpContext context)
   en ASP.registropostular_formcaptcharecupero_aspx.ProcessRequest(HttpContext context) en c:\Users\clurgo\AppData\Local\Temp\Temporary ASP.NET Files\webrh\df8a7146\84c3bc9a\App_Web_vbyupnyy.0.cs:línea 0
   en System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   en System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
